### ISSUE TITLE
Function get(&self, i: usize)

### ISSUE THREAD

**Issue by hanusek** [contain-rs/bit-vec#66]
https://docs.rs/bit-vec/0.5.0/bit_vec/struct.BitVec.html#method.get

Function returns MSB. I need LSB. How do it?

**Comment by callpraths** [comment]
Could you post example code for what you're trying to do?
`v.get(v.len()-1).unwrap() // Index definitely in range`
should get you the LSB in the BitVec.

**Comment by pczarn** [comment]
Cześć @hanusek . Function returns the MSB, because `from_bytes` puts MSB first: "the most significant bits of each byte [is] coming first." `to_bytes` works in a similar manner.

Like @callpraths mentioned, you need to do some substracting from `len()` or use modulo to do `idx-idx%8+8-idx%8`.

We may want to create some variant of `from_bytes` that puts the LSB first.
